<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ClientSetting extends Model
{
    protected $fillable = [
        'client_id',
        'business_mode',
        'retail_pos_enabled',
        'wholesale_pos_enabled',
        'purchases_enabled',
        'suppliers_enabled',
        'customers_enabled',
        'inventory_enabled',
        'expiry_alerts_enabled',
        'cash_drawer_enabled',
        'cash_drawer_alert_threshold',
        'accounts_enabled',
        'reports_enabled',
        'insurance_enabled',
        'efris_enabled',
        'employees_enabled',
        'proforma_enabled',
        'dispensing_price_guide_enabled',
        'support_enabled',
        'accounting_chart_enabled',
        'accounting_general_ledger_enabled',
        'accounting_trial_balance_enabled',
        'accounting_journals_enabled',
        'accounting_vouchers_enabled',
        'accounting_profit_loss_enabled',
        'accounting_balance_sheet_enabled',
        'accounting_expenses_enabled',
        'accounting_fixed_assets_enabled',
        'show_purchase_price_in_pos',
        'show_last_purchase_price_in_pos',
        'hide_out_of_stock_in_search',
        'allow_small_receipt',
        'allow_small_invoice',
        'allow_large_receipt',
        'allow_large_invoice',
        'allow_small_proforma',
        'allow_large_proforma',
        'hide_discount_line_on_print',
        'currency_symbol',
        'tax_label',
        'tax_number',
        'efris_environment',
        'efris_transport_mode',
        'efris_tin',
        'efris_legal_name',
        'efris_business_name',
        'efris_branch_code',
        'efris_device_serial',
        'efris_auth_url',
        'efris_submission_url',
        'efris_reversal_url',
        'efris_username',
        'efris_password',
        'efris_client_id',
        'efris_client_secret',
        'receipt_header',
        'receipt_footer',
        'invoice_footer',
        'report_footer',
        'show_logo_on_print',
        'show_branch_contacts_on_print',
        'default_line_count',
        'allow_add_one_line',
        'allow_add_five_lines',
    ];

    protected $casts = [
        'retail_pos_enabled' => 'boolean',
        'wholesale_pos_enabled' => 'boolean',
        'purchases_enabled' => 'boolean',
        'suppliers_enabled' => 'boolean',
        'customers_enabled' => 'boolean',
        'inventory_enabled' => 'boolean',
        'expiry_alerts_enabled' => 'boolean',
        'cash_drawer_enabled' => 'boolean',
        'cash_drawer_alert_threshold' => 'decimal:2',
        'accounts_enabled' => 'boolean',
        'reports_enabled' => 'boolean',
        'insurance_enabled' => 'boolean',
        'efris_enabled' => 'boolean',
        'employees_enabled' => 'boolean',
        'proforma_enabled' => 'boolean',
        'dispensing_price_guide_enabled' => 'boolean',
        'support_enabled' => 'boolean',
        'accounting_chart_enabled' => 'boolean',
        'accounting_general_ledger_enabled' => 'boolean',
        'accounting_trial_balance_enabled' => 'boolean',
        'accounting_journals_enabled' => 'boolean',
        'accounting_vouchers_enabled' => 'boolean',
        'accounting_profit_loss_enabled' => 'boolean',
        'accounting_balance_sheet_enabled' => 'boolean',
        'accounting_expenses_enabled' => 'boolean',
        'accounting_fixed_assets_enabled' => 'boolean',
        'show_purchase_price_in_pos' => 'boolean',
        'show_last_purchase_price_in_pos' => 'boolean',
        'hide_out_of_stock_in_search' => 'boolean',
        'allow_small_receipt' => 'boolean',
        'allow_small_invoice' => 'boolean',
        'allow_large_receipt' => 'boolean',
        'allow_large_invoice' => 'boolean',
        'allow_small_proforma' => 'boolean',
        'allow_large_proforma' => 'boolean',
        'hide_discount_line_on_print' => 'boolean',
        'show_logo_on_print' => 'boolean',
        'show_branch_contacts_on_print' => 'boolean',
        'allow_add_one_line' => 'boolean',
        'allow_add_five_lines' => 'boolean',
        'default_line_count' => 'integer',
        'efris_username' => 'encrypted',
        'efris_password' => 'encrypted',
        'efris_client_id' => 'encrypted',
        'efris_client_secret' => 'encrypted',
    ];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }
}
